image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  CONTAINER_UI_IMAGE: dlike/folls.ui:$CI_COMMIT_SHA
  CONTAINER_API_IMAGE: dlike/folls.api:$CI_COMMIT_SHA

build:
  stage: build
  script:
    - echo $DOCKER_PASS
    - echo $DOCKER_PASS | docker login -u $DOCKER_LOGIN --password-stdin
    - docker build --pull -t $CONTAINER_UI_IMAGE ./Folls.UI
    - docker push $CONTAINER_UI_IMAGE
    - docker build --pull -t $CONTAINER_API_IMAGE ./Folls.API
    - docker push $CONTAINER_API_IMAGE
  only:
    - develop

deploy:
  stage: deploy
  image: alpine
  environment:
    name: develop
  script:
    - apk update && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config set-cluster blue-cluster --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --username="$KUBE_USER" --password="$KUBE_PASS"
    - kubectl config set-context default --cluster=blue-cluster --user=admin
    - kubectl config use-context default
    - kubectl config view
    - sed 's,{{image}},'"$CONTAINER_UI_IMAGE"',g' ./kube/folls.ui.yml > ./kube/folls.ui.yml
    - sed 's,{{image}},'"$CONTAINER_API_IMAGE"',g' ./kube/folls.api.yml > ./kube/folls.api.yml
    - sed 's,{{namespace}},develop,g' ./kube/folls.namespace.yml > ./kube/folls.namespace.yml
    - sed 's,{{subdomain}},develop.,g' ./kube/folls.ingress.yml > ./kube/folls.ingress.yml
    - cat ./kube/folls.namespace.yml
    - kubectl apply -f ./kube/folls.namespace.yml
    - kubectl apply -n develop -f ./kube/
  only:
    - develop


