version: '3'
services:
  ui:
    build:
      context: ./Folls.UI
      dockerfile: dev.Dockerfile
    restart: always
    container_name: folls.ui
    volumes:
      - ./Folls.UI/fe:/app
    ports:
      - 5002:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: folls-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
