apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: folls.ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: folls.ui
  template:
    metadata:
      labels:
        app: folls.ui
    spec:
      containers:
      - name: folls-ui
        image: dlike/folls.ui:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: Something
            value: "Test14"
          - name: VUE_APP_API_BASE_URL
            value: "/api/api"
          - name: NODE_ENV
            value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: folls-ui
  labels:
    app: folls.ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: folls.ui

