apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: folls.ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: folls.ui
  template:
    metadata:
      labels:
        app: folls.ui
    spec:
      containers:
      - name: folls-ui
        image: dlike/folls.ui:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: Something
            value: "Test3"
